import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const silka = localFont({
  src: [
    {
      path: "../fonts/silka-regular-webfont.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../fonts/silka-regularitalic-webfont.woff2",
      weight: "400",
      style: "italic",
    },
    {
      path: "../fonts/silka-medium-webfont.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "../fonts/silka-mediumitalic-webfont.woff2",
      weight: "500",
      style: "italic",
    },
    {
      path: "../fonts/silka-semibold-webfont.woff2",
      weight: "600",
      style: "normal",
    },
  ],
  variable: "--font-silka",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${silka.variable} antialiased`}
        suppressHydrationWarning
      >
        {children}
      </body>
    </html>
  );
}
